### ISSUE TITLE
feature: - Admin create Events

### ISSUE THREAD

**Issue by Peter-Peter254** [LaravelKenya/Laravel-Kenya#14]
@rono516  Let me know if you are able to access admin dashboard on both the dev and prod environment. I can then start on events creation from the admin side.

**Comment by rono516** [comment]
I can access on dev. I think it's alright if you can work on the events creation.

**Comment by Peter-Peter254** [comment]
Okay.. Do you mind like pasting the figma design somewhere on the repo. I may need to see what an event will contain.

Thanks.

**Comment by rono516** [comment]
[Here it is](https://www.figma.com/file/bONK4JnCwdpSZuhDKwpgcV/Laraevl-Kenya?type=design&node-id=19%3A1924&mode=design&t=vQXGCpODmcEJWAEC-1) . I think the initial design didn't factor in the design for admin side. You can implement it however possible but just incorporate near those colors in the design.

**Comment by Peter-Peter254** [comment]
Sure. Thanks
