### ISSUE TITLE
Setup  Admin Panel.

### ISSUE THREAD

**Issue by Peter-Peter254** [LaravelKenya/Laravel-Kenya#9]
Was thinking about jumping to Creation of events from the admin side. This will definitely require an admin dashboard. Was thinking of setting it up using filament. Let me know your thoughts.

**Comment by rono516** [comment]
Hello Peter, this is well appreciated. Set it up as an addition to what we currently. @kemboi22

**Comment by rono516** [comment]
[PR](https://github.com/LaravelKenya/Laravel-Kenya/pull/13)
